

import  {encode_sha256} from  "../src/utils/encode";

import {onRequestGet as authOnGet} from "./auth"
import {onRequestPost as authOnPost} from "./auth"

async function errorHandling(context) {
  try {
    return await context.next();
  } catch (err) {
    return new Response(`${err.message}\n${err.stack}`, { status: 500 });
  }
}



export async function home(context) {
  const {request, env} = context;

  var url = new URL(request.url);

  if(url.pathname == "/"){
    const html = `<!DOCTYPE html>
    <body>
      <h1>Hello World</h1>
      <p>This markup was generated by a Cloudflare Page.</p>

    </body>`;

    return new Response(html, {
      headers: {
        "content-type": "text/html;charset=UTF-8",
      },
    });
    
  }




  url.pathname = "/auth";



  const newRequest = new Request(url, request );
  // return fetch(newRequest);

  console.log(`newRequest: ${newRequest.url}`);

    return context.next();
}

export const onRequest = [
  // errorHandling, 
  home];