# Top-level configuration
name = "cf-fns"
compatibility_date = "2025-04-27"
pages_build_output_dir = "./public/dist"
[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "D1"
database_id = "61e72254-2756-4ee8-a4e4-7a270a06e48a"

[[kv_namespaces]]
binding = "KV"
id = "9a1ad11316c9444d902518c863629fa4"

[[r2_buckets]]
bucket_name = "r2disk"
binding = "r2disk"
