[package]
name = "nx_mem"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.19"  # or latest stable
log = "0.4.6"
lazy_mut = "0.2.1"
hashbrown = "0.15.3"


[profile.release]
opt-level = "z"
lto = true
# codegen-units = 1
[build-dependencies]
cc = "1.0"