
[alias] 
bb="build --release --target wasm32-wasip1 --target-dir /tmp/cargo/build/wasi-rust" 
ii="install --locked --target wasm32-wasip1 --target-dir /tmp/cargo/wasi-rust --path .  --root /tmp/cargo/install/wasi-rust" 
