export function greeting(name: string): Response {

    const html = `<!DOCTYPE html>
    <body>
      <h1>Hello ${name}</h1>
      <p>This markup was generated by a Cloudflare Page.</p>
    </body>`;

    return new Response(html, {
      headers: {
        "content-type": "text/html;charset=UTF-8",
      },
    });


  }